import example from "../images/example.png";

// eslint-disable-next-line no-unused-vars
let products = [
  [
    {
      id: 0,
      title: "Broom with Dust Pan",
      image: example,
      price: 10,
      sold: 123,
    },
    {
      id: 1,
      title: "Interesting Book",
      image: example,
      price: 15,
      sold: 234,
    },
    {
      id: 2,
      title: "Wood Puzzle",
      image: example,
      price: 12,
      sold: 0,
    },
    {
      id: 3,
      title: "Beanie",
      image: example,
      price: 29,
      sold: 32,
    },
    {
      id: 4,
      title: "Black T-Shirt",
      image: example,
      price: 9.99,
      sold: 0,
    },
    {
      id: 5,
      title: "Headset",
      image: example,
      price: 65,
      sold: 345,
    },
    {
      id: 6,
      title: "Alarm Clock",
      image: example,
      price: 20,
      sold: 0,
    },
    {
      id: 7,
      title: "Sunglasses",
      image: example,
      price: 140,
      sold: 46,
    },
    {
      id: 8,
      title: "Jeans",
      image: example,
      price: 79.99,
      sold: 46,
    },
    {
      id: 9,
      title: "Sneakers",
      image: example,
      price: 150,
      sold: 46,
    },
  ],
  [
    {
      id: 10,
      title: "Honey Packaging",
      image: example,
      price: 42,
      sold: 46,
    },
    {
      id: 11,
      title: "Belt",
      image: example,
      price: 8.99,
      sold: 0,
    },
    {
      id: 12,
      title: "Belt",
      image: example,
      price: 8.99,
      sold: 0,
    },
    {
      id: 13,
      title: "Belt",
      image: example,
      price: 8.99,
      sold: 0,
    },
    {
      id: 14,
      title: "Belt",
      image: example,
      price: 8.99,
      sold: 465,
    },
    {
      id: 15,
      title: "Belt",
      image: example,
      price: 8.99,
      sold: 0,
    },
    {
      id: 16,
      title: "Belt",
      image: example,
      price: 8.99,
      sold: 0,
    },
    {
      id: 17,
      title: "Belt",
      image: example,
      price: 8.99,
      sold: 46,
    },
    {
      id: 18,
      title: "Belt",
      image: example,
      price: 8.99,
      sold: 0,
    },
    {
      id: 19,
      title: "Belt",
      image: example,
      price: 8.99,
      sold: 354,
    },
  ],
  [
    {
      id: 20,
      title: "Belt",
      image: example,
      price: 8.99,
      sold: 0,
    },
    {
      id: 21,
      title: "Belt",
      image: example,
      price: 8.99,
      sold: 0,
    },
    {
      id: 22,
      title: "Belt",
      image: example,
      price: 8.99,
      sold: 5,
    },
    {
      id: 23,
      title: "Belt",
      image: example,
      price: 8.99,
      sold: 0,
    },
    {
      id: 24,
      title: "Belt",
      image: example,
      price: 8.99,
      sold: 0,
    },
    {
      id: 25,
      title: "Belt",
      image: example,
      price: 8.99,
      sold: 0,
    },
    {
      id: 26,
      title: "Belt",
      image: example,
      price: 8.99,
      sold: 0,
    },
    {
      id: 27,
      title: "Belt",
      image: example,
      price: 8.99,
      sold: 0,
    },
    {
      id: 28,
      title: "Belt",
      image: example,
      price: 8.99,
      sold: 0,
    },
    {
      id: 29,
      title: "Belt",
      image: example,
      price: 8.99,
      sold: 0,
    },
  ],
  [
    {
      id: 30,
      title: "Belt",
      image: example,
      price: 8.99,
      sold: 0,
    },
    {
      id: 31,
      title: "Belt",
      image: example,
      price: 8.99,
      sold: 0,
    },
    {
      id: 32,
      title: "Belt",
      image: example,
      price: 8.99,
      sold: 0,
    },
  ],
];

export default products;
